"""
Example Usage of PowerShell Agent (v0.3.0 package structure)
Demonstrates: basic execution, parallel commands, agentic loop, file writing, session history, and GitHub MCP.
"""

import asyncio
import os
from powershell_agent import PowerShellAgent, list_sessions
from powershell_agent.executor import run_powershell
from powershell_agent.tools import build_default_registry


async def example_1_basic_command():
    """Execute a simple command and inspect the result dict."""
    print("\n" + "="*72)
    print("EXAMPLE 1: Basic Command Execution")
    print("="*72)
    result = await run_powershell("Get-Date", stream_output=True)
    print(f"\nResult status : {result['status']}")
    print(f"Return code   : {result['return_code']}")


async def example_2_parallel_commands():
    """Run multiple commands concurrently via asyncio.gather."""
    print("\n" + "="*72)
    print("EXAMPLE 2: Parallel Execution")
    print("="*72)
    tasks = [
        run_powershell("Get-ChildItem -Filter *.py", stream_output=False),
        run_powershell("Get-ChildItem -Filter *.md", stream_output=False),
        run_powershell("Get-Date", stream_output=False),
    ]
    results = await asyncio.gather(*tasks)
    for r in results:
        print(f"  [{r['status']}] {r['command'][:60]}")


async def example_3_write_file_tool():
    """Use the write_file tool directly."""
    print("\n" + "="*72)
    print("EXAMPLE 3: Write File Tool")
    print("="*72)
    registry = build_default_registry()
    result = await registry.call("write_file", {
        "path": "example_output.txt",
        "content": "Generated by PowerShell Agent example\n",
    })
    print(f"  {result['output']}")


async def example_4_agentic_loop():
    """Full agentic loop — LLM decides which commands to run."""
    print("\n" + "="*72)
    print("EXAMPLE 4: Agentic Loop")
    print("="*72)
    agent = PowerShellAgent()
    response = await agent.run("Find all Python files in the current directory and count them")
    print(f"\nAgent response:\n{response}")


async def example_5_session_history():
    """Show saved sessions from disk."""
    print("\n" + "="*72)
    print("EXAMPLE 5: Session History")
    print("="*72)
    sessions = list_sessions(limit=5)
    if not sessions:
        print("  No sessions yet — run the agent first.")
    for s in sessions:
        print(f"  {s['id']}  {s['started_at'][:19]}  iter={s['iterations']}  {s['prompt_preview'][:50]}")


async def example_6_custom_tool():
    """Register a custom tool and use it with the agent."""
    print("\n" + "="*72)
    print("EXAMPLE 6: Custom Tool Registration")
    print("="*72)

    registry = build_default_registry()

    # Register a custom tool that echoes back its input
    custom_schema = {
        "type": "function",
        "function": {
            "name": "echo_message",
            "description": "Echo back a message (demo custom tool).",
            "parameters": {
                "type": "object",
                "properties": {"message": {"type": "string"}},
                "required": ["message"],
            },
        },
    }

    async def echo_handler(message: str, **_):
        return {"status": "success", "output": f"ECHO: {message}", "error": None, "return_code": 0}

    registry.register(custom_schema, echo_handler)
    print(f"  Registered tools: {[s['function']['name'] for s in registry.schemas()]}")


async def run_all():
    for fn in [
        example_1_basic_command,
        example_2_parallel_commands,
        example_3_write_file_tool,
        example_4_agentic_loop,
        example_5_session_history,
        example_6_custom_tool,
    ]:
        await fn()
        await asyncio.sleep(0.5)


if __name__ == "__main__":
    print("PowerShell Agent: Examples (v0.3.0)")
    asyncio.run(run_all())
    print("\n✅ All examples finished!")
